# Generated by Django 2.0.7 on 2020-02-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200229_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
